use_frameworks!

platform :ios, '8.0'

target 'GLTools_Example' do
    
  
  pod 'SnapKit', '~> 4.0.0'
  pod 'Kingfisher', '~> 4.0.0'
  #pod 'Alamofire', '~> 4.4'
  pod 'GLTools', :path => '../'
  
  use_frameworks!

  target 'GLTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'

  end
  
end
